### ISSUE TITLE
XMonad.Hooks.RefocusLast is unstable

### ISSUE THREAD

**Issue by jcguu95** [Lenivaya/dotfiles#1]
Hello,

Thanks for your config. It is amazing, especially your `xmonad` setup! I hope I can make it work, but compiling with your config leads to an error: 

> lib/XMonad/Custom/Event.hs:12:1: error:
>   Could not find module `XMonad.Hooks.RefocusLast`

The module is in the package [xmonad-contrib](https://hackage.haskell.org/package/xmonad-contrib-0.16/docs/XMonad-Hooks-RefocusLast.html). However, as the official site shows, this package is unstable.. I wonder if that's the reason it breaks.

Does it still work for you? I have 

```
services.xserver.windownManager.xmonad.extraPackages = haskellPackages: [ haskellPackages.xmonad-contrib];
```

in my `configuration.nix`.. so I think I do have the package.

**Comment by cureforpain** [comment]
I checked your config and seems like i have quick-fix for you

Just add unstable channel
```
sudo nix-channel --add "https://nixos.org/channels/nixpkgs-unstable" unstable
```
And then in your configuration.nix
```nix
nixpkgs.overlays = [
  (self: super:
    with super; {
      my = {
        unstable = import <unstable> { inherit config; };
    })
];

```
Now you can access unstable via pkgs.unstable, this is exactly what we need because we want install xmonad from unstable channel( especially xmonad-contrib, which is only 0.15 version on stable channel  )

And all you have to do is to set xmonad.haskellPackages to use unstable channel:
```nix
services.xserver.windowManager.xmonad.haskellPackages = pkgs.unstable.haskellPackages;
```

**Comment by cureforpain** [comment]
While i was writing this i noticed "xmonad-contrib_0_16" package, but i still recommend to install xmonad from unstable so as not to wait for releases for a long time.

**Comment by jcguu95** [comment]
Thanks so much for reaching out!

I added the unstable channel, and added the following in to my `configuration.nix`:

```
nixpkgs.overlays = [
  (self: super:
    with super; {
      my = {
        unstable = import <unstable> { inherit config; };
    };})  ### trivial fix here
];

services.xserver.windowManager.xmonad.haskellPackages = pkgs.unstable.haskellPackages;
```

But it seems that `unstable.HaskellPackages` does not exist, as suggested by the error message:

```
attribute 'unstable' missing, at..
```

I've also tried `pkgs.haskellPackages.unstable` and `pkgs.unstableHaskellPackages` without luck.


---

I should say I'm very new to nixOS. There might be an easy fix that I don't know. I will level up my skills and come back later :) Thank you!

**Comment by cureforpain** [comment]
Well, seems like it's just my typo

Try this, should work
```nix
nixpkgs.overlays = [
  (self: super:
    with super; {  
        unstable = import <unstable> { inherit config; };
    }) 
];
```

**Comment by jcguu95** [comment]
That solves this particular issue. Thank you.

Though there's another complaint of not finding this [package](https://hackage.haskell.org/package/gloss-1.13.1.2/docs/Graphics-Gloss-Interface-Environment.html), I should close this as it's another issue.

**Comment by cureforpain** [comment]
Add gloss to haskellPackages and all must compile

**Comment by jcguu95** [comment]
Compiled. Wow. Gorgeous :+1:
